{
 "title": "Network Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Most Recent SpeedTest Result",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  server as 'Server',\n  dl as 'Download',\n  ul as 'Upload',\n  ping as 'Ping'\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "SpeedTest Server Location (Last 24 Hours)",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  server AS metric,\n  lat AS \"Latitude\",\n  lon AS \"Longitude\",\n  dl AS \"Download\",\n  ul AS \"Upload\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "SpeedTest Server Location",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select distinct server as \"Server Location\",\ncount(server) as \"Test Count\"\nfrom results\nwhere $__timeFilter(timestamp)\ngroup by server\norder by count(server) desc\n"
    }
   ]
  },
  {
   "title": "Download/Upload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  dl as \"Download\",\n  ul as \"Upload\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Ping Results (Timeline)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  ping\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Speed Avg - 24 Hrs.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  AVG(dl) as \"Download\",\n  AVG(ul) as \"Upload\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Speed Avg - 12 Hrs.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  AVG(dl) as \"Download\",\n  AVG(ul) as \"Upload\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Avg. Ping - 24 hrs.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  AVG(ping) as \"Ping\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Avg. Ping - 12 hrs.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  AVG(ping) as \"Ping\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Ping Results (Latest)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  ping\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Speed Avg - 6 Hrs.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  AVG(dl) as \"Download\",\n  AVG(ul) as \"Upload\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Speed Avg - 1 Hr.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  AVG(dl) as \"Download\",\n  AVG(ul) as \"Upload\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Avg. Ping - 6 hrs.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  AVG(ping) as \"Ping\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Avg. Ping - 1 hr.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  AVG(ping) as \"Ping\"\nFROM results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}